name: outdoor.movie
favicon: null
layout_spectrum: 0.9261688021942973
typography_spectrum: 0.8790376966353506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.13540929346345365
  lightness: 0.6209342507645488
  saturation: 0.3312880643643439
  rhythmicContrast: 0.2135904715396464
purpose: []
